### ISSUE TITLE
demo website broken with 404

### ISSUE THREAD

**Issue by monperrus** [Ifsttar/qrtone#26]
The super cool demo site at https://ifsttar.github.io/qrtone/ is now 404.

Would be great to have it up again to demo qrtone live :)

**Comment by nicolas-f** [comment]
Hello,

Thanks the organization is now Universite-Gustave-Eiffel so I have to rename it

https://universite-gustave-eiffel.github.io/qrtone/

**Comment by monperrus** [comment]
cool, thanks!
