### ISSUE TITLE
Android Implementation  

### ISSUE THREAD

**Issue by KaleabK** [Ifsttar/qrtone#9]
@nicolas-f  Can you share android implementation of the library or any guide

**Comment by nicolas-f** [comment]
Hi,
Good morning, sir,

For the moment you can test an early non final version of the library with the following Android project:

https://github.com/Ifsttar/qrtone-android

**Comment by KaleabK** [comment]
The inaudiable range doesn't transfer data. Note: a mobile device have
filter it doesn't detect upto 22khz

**Comment by nicolas-f** [comment]
Only the default audible configuration will be retained, the frequency choices will no longer be configurable to ensure compatibility between implementations.

**Comment by nicolas-f** [comment]
https://github.com/Ifsttar/qrtone-android
